### ISSUE TITLE
Typo in Antragsteller: VorherigeresBeschaeftigungsverhaeltnis sollte VorherigesBeschaeftigungsverhaeltnis

### ISSUE THREAD

**Issue by triegmann** [hypoport/kreditsmart-kex-vorgang-api-schema#1]
Im Schema Antragsteller wird das Attribut VorherigeresBeschaeftigungsverhaeltnis mit dem Typ VorherigesBeschaeftigungsverhaeltnis.
Das Attribute sollte denselben Namen tragen wie der Typ.
Bei mir kam es hierdurch zu einem Fehler meines POCO-Generators.

**Comment by mikegeiss** [comment]
Vielen Dank für den Hinweis. Haben das nun gefixed.
